    [package]
    name = "flags-2-env-sidecar"
    version = "0.1.0"
    edition = "2021"
    license = "MIT"
    description = "Sidecar for flags-2-env"
    repository = "https://github.com/flags-2-env/flags-2-env-sidecar.rs"

    [[bin]]
    name = "flags2env-platform-sidecar"
    path = "src/main.rs"

    [dependencies]
    serde = { version = "1", features = ["derive"] }
    serde_json = "1"
    thiserror = "2"

[lints.rust]
unsafe_code = "forbid"


